src/se/plushogskolan/web/domain/cars/Brand.java
package se.plushogskolan.web.domain.cars;

/**
 * An enum representing a car brand.
 */
public enum Brand {

	VOLVO("Volvo", "volvo_200.jpg", "volvo_100.jpg"), MERCEDES("Mercedes", "mercedes_200.jpg", "mercedes_100.jpg"), RENAULT(
			"Renault", "renault_200.jpg", "renault_100.jpg"), VW("Volkswagen", "volkswagen_200.jpg",
			"volkswagen_100.jpg");

	private String niceName;
	private String logo200px;
	private String logo100px;

	private Brand(String niceName, String logo200, String logo100) {
		this.niceName = niceName;
		this.logo200px = logo200;
		this.logo100px = logo100;
	}

	public String getNiceName() {
		return niceName;
	}

	public String getLogo100px() {
		return logo100px;
	}

	public String getLogo200px() {
		return logo200px;
	}

}

src/se/plushogskolan/web/domain/cars/Car.java
package se.plushogskolan.web.domain.cars;

public class Car {

	private String regNo;
	private int yearModel;
	private Brand brand;
	private double fuelConsumption;
	private Owner owner;

	public Car() {

	}

	public Car(String regNo, int yearModel, Brand brand, double fuelConsumption, Owner owner) {
		setRegNo(regNo);
		setYearModel(yearModel);
		setBrand(brand);
		setFuelConsumption(fuelConsumption);
		setOwner(owner);
	}

	public String getRegNo() {
		return regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	public int getYearModel() {
		return yearModel;
	}

	public void setYearModel(int yearModel) {
		this.yearModel = yearModel;
	}

	public double getFuelConsumption() {
		return fuelConsumption;
	}

	public void setFuelConsumption(double fuelConsumption) {
		this.fuelConsumption = fuelConsumption;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public Owner getOwner() {
		return owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	@Override
	public String toString() {
		return "Car [regNo=" + regNo + ", yearModel=" + yearModel + ", brand=" + brand + ", fuelConsumption="
				+ fuelConsumption + ", owner=" + owner + "]";
	}

}

src/se/plushogskolan/web/domain/cars/CarService.java
package se.plushogskolan.web.domain.cars;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A singleton CarService. Singleton means there can be only one instance, and
 * that instance is shared by all java classes. A CarService is retrieved by
 * calling the static getInstance() method.
 * 
 */
public class CarService {

    private static CarService service;

    private Map<String, Owner> owners = new HashMap<String, Owner>();
    private Map<String, Car> cars = new HashMap<String, Car>();

    public static CarService getInstance() {
        if (service == null) {
            service = new CarService();
        }
        return service;
    }

    /**
     * A private constructor. This class can not be created from the outside.
     * You need to use the getInstance() method to get an instance of
     * CarService.
     */
    private CarService() {

        Owner olle = new Owner("19800423-6545", "Olle", "Persson",
                "Storgatan 1", "416 72", "Göteborg");
        Owner kalle = new Owner("19920901-9812", "Kalle", "Johansson",
                "Torggatan 14", "412 23", "Göteborg");

        Car car1 = new Car("ABC-123", 2005, Brand.MERCEDES, 0.45, olle);
        Car car2 = new Car("DEF-456", 2011, Brand.VW, 0.56, kalle);
        Car car3 = new Car("GHI-789", 2013, Brand.VOLVO, 0.51, kalle);

        olle.getCars().add(car1);
        kalle.getCars().add(car2);
        kalle.getCars().add(car3);

        owners.put(olle.getSocialSecurityNo(), olle);
        owners.put(kalle.getSocialSecurityNo(), kalle);
        cars.put(car1.getRegNo(), car1);
        cars.put(car2.getRegNo(), car2);
        cars.put(car3.getRegNo(), car3);

    }

    public Car getCarByRegNo(String regNo) {
        return cars.get(regNo);
    }

    public List<Car> getCars() {
        return new ArrayList<Car>(cars.values());
    }

    public List<Owner> getOwners() {
        return new ArrayList<Owner>(owners.values());
    }

    public Owner getOwnerBySocialSecurityNo(String socialSecurityNo) {
        return owners.get(socialSecurityNo);
    }

    public void createOrUpdateCar(Car car) {
        cars.put(car.getRegNo(), car);
    }

}

src/se/plushogskolan/web/domain/cars/Owner.java
package se.plushogskolan.web.domain.cars;

import java.util.HashSet;
import java.util.Set;

public class Owner {
	private String socialSecurityNo;
	private String firstName;
	private String lastName;
	private String address;
	private String zipCode;
	private String city;
	private Set<Car> cars = new HashSet<Car>();

	public Owner() {

	}

	public Owner(String socialSecurityNo, String firstName, String lastName, String address, String zipCode, String city) {
		setSocialSecurityNo(socialSecurityNo);
		setFirstName(firstName);
		setLastName(lastName);
		setAddress(address);
		setZipCode(zipCode);
		setCity(city);

	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set<Car> getCars() {
		return cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

	public String getSocialSecurityNo() {
		return socialSecurityNo;
	}

	public void setSocialSecurityNo(String socialSecurityNo) {
		this.socialSecurityNo = socialSecurityNo;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getFullName() {

		return getFirstName() + " " + getLastName();
	}

	@Override
	public String toString() {
		return "Owner [socialSecurityNo=" + socialSecurityNo + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", no of cars=" + cars.size() + "]";
	}

}

WebContent/WEB-INF/jsp/plusverkstaden/carForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html class="no-js">
	<head>
		<%@ include file="head.jsp" %>
		<%@ include file="styles.jsp" %>
	</head>
<body class="page-car-form">
	
	<%@ include file="page-header.jsp" %>
	<%@ include file="navigation.jsp" %>
	
	<section id="main">
		<div class="clearfix">
			
			<c:set value="Add new car" var="pageTitle"/>
			<c:if test="${not empty car}">
				<c:set value="Edit car ${car.regNo}" var="pageTitle"/>
			</c:if>
			
			<jsp:include page="page-title.jsp">
				<jsp:param name="title" value="${pageTitle}" />
			</jsp:include>
			
			<c:forEach items="${errors}" var="error">
				<p>${error}</p>
			</c:forEach>
			
			<form action="<c:url value="/plusverkstaden/carForm.servlet" />" method="post">
				<div class="form-item">
					<label for="regno">Reg no</label>
					<c:if test="${not empty car}">
						${car.regNo}
					</c:if>
					<c:if test="${empty car}">
						<input type="text" name="regno" id="regno" value="" pattern="[a-zA-Z]{3}-[0-9]{3}" placeholder="ABC-123" />
					</c:if>
				</div>
				<div class="form-item">
					<label for="year">Year</label>
					<input type="number" name="year" id="year" value="${car.yearModel}" min="1970" max="2013" placeholder="2013" />
				</div>
				<div class="form-item">
					<label for="brand">Brand</label>
					<select name="brand" id="brand">
						<option value="">Select brand</option>
						<c:forEach items="${brands}" var="brand">
							<c:if test="${car.brand.niceName eq brand.niceName }">
								<c:set value="selected" var="selected" />
							</c:if>
							<option value="${brand}" ${selected}>${brand.niceName}</option>
							<c:remove var="selected"/>
						</c:forEach>
					</select>
				</div>
				<div class="form-item">
					<label for="fuelConsumption">Fuel consumption</label>
					<input type="text" name="fuelConsumption" id="fuelConsumption" value="${car.fuelConsumption}" placeholder="1.0" /><span class="field-suffix">l / 10km</span>
				</div>
				<div class="form-item">
					<label for="owner">Owner</label>
					<select name="owner" id="owner">
						<option value="">Select owner</option>
						<c:forEach items="${owners}" var="owner">
							<c:if test="${car.owner.socialSecurityNo eq owner.socialSecurityNo }">
								<c:set value="selected" var="selected" />
							</c:if>
							<option value="${owner.socialSecurityNo}" ${selected}>${owner.fullName}</option>
							<c:remove var="selected"/>
						</c:forEach>
					</select>
				</div>

				<div class="form-actions">
					<c:set value="Add" var="submitTitle"/>
					<c:if test="${not empty car}">
						<c:set value="Update" var="submitTitle"/>
					</c:if>
					<input type="submit" name="submit" value="${submitTitle}" />
					<a href="<% out.print(request.getContextPath()); %>/plusverkstaden/listCars.servlet">Cancel</a>
				</div>
				<input type="hidden" name="op" value="${op}" />
				<c:if test="${not empty car}">
					<input type="hidden" name="regno" value="${car.regNo}" />
				</c:if>
			</form>
		</div>
	</section>
	
	<%@ include file="footer.jsp" %>
</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/error-dummy-exception.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="pvn-tag" tagdir="/WEB-INF/tags" %>
<%@ page isErrorPage="true" %>
<!DOCTYPE html>
<html class="no-js">
	<head>
		<%@ include file="head.jsp" %>
		<%@ include file="styles.jsp" %>
	</head>
<body class="error-page">
	
	<%@ include file="page-header.jsp" %>
	<%@ include file="navigation.jsp" %>
	
	<section id="main">
		<div class="clearfix">
			<img src="<% out.print(request.getContextPath()); %>/images/error.png" alt="ERROR" />
			<jsp:include page="page-title.jsp">
				<jsp:param name="title" value="Something bad happend" />
			</jsp:include>
			<p><strong>An exception was thrown:</strong></p>
			<p>${pageContext.exception}</p>
			
		</div>
	</section>
	
	<%@ include file="footer.jsp" %>
</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/error404.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="pvn-tag" tagdir="/WEB-INF/tags" %>

<!DOCTYPE html>
<html class="no-js">
	<head>
		<%@ include file="head.jsp" %>
		<%@ include file="styles.jsp" %>
	</head>
<body class="error-page">
	
	<%@ include file="page-header.jsp" %>
	<%@ include file="navigation.jsp" %>
	
	<section id="main">
		<div class="clearfix">
			<img src="<% out.print(request.getContextPath()); %>/images/404.jpg" alt="404 ERROR" />
			<jsp:include page="page-title.jsp">
				<jsp:param name="title" value="404 ERROR" />
			</jsp:include>
			
			<p><strong>Page not found</strong></p>
			<p>How about going back to the <a href="<c:url value="/plusverkstaden/listCars.servlet" />">start page?</a></p>
			
		</div>
	</section>
	
	<%@ include file="footer.jsp" %>
</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<footer id="footer">
	<div>
		<h1>Recently edited cars</h1>
		<ul>
			<c:forEach items="${edited_cars}" var="car">
				<li><a href="<c:url value="viewCar.servlet?regNo=${car.regNo}"/>">${car.regNo}  - ${car.owner.fullName}</a></li>
			</c:forEach>
		</ul>
	</div>
</footer>

WebContent/WEB-INF/jsp/plusverkstaden/head.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta charset="utf-8" />
<title>List cars - Plusverkstaden</title>

WebContent/WEB-INF/jsp/plusverkstaden/listCars.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="pvn-tag" tagdir="/WEB-INF/tags" %>

<!DOCTYPE html>
<html class="no-js">
	<head>
		<%@ include file="head.jsp" %>
		<%@ include file="styles.jsp" %>
	</head>
<body>
	
	<%@ include file="page-header.jsp" %>
	<%@ include file="navigation.jsp" %>
	
	<section id="main">
		<div>
			<jsp:include page="page-title.jsp">
				<jsp:param name="title" value="List cars" />
			</jsp:include>

			<pvn-tag:listCars items="${cars}"/>
		</div>
	</section>
	
	<%@ include file="footer.jsp" %>
</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/navigation.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="pvn" uri="se.plushogskolan.plusverkstaden" %>
<nav id="mainmenu" class="clearfix">
	<div>
		<ul>
			<li class="active"><a href="<c:url value="/plusverkstaden/listCars.servlet"/>" class="active">Home</a></li>
			<li><a href="<c:url value="/plusverkstaden/carForm.servlet"/>"> Add new car</a></li>
			<li><a href="<c:url value="/plusverkstaden/broken-url"/>">Broken URL</a></li>
		</ul>
		<span class="time">${pvn:getDate("Y-MM-dd HH:mm")}</span>
	</div>
</nav>

WebContent/WEB-INF/jsp/plusverkstaden/page-header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<header id="header">
	<div class="clearfix">
		<h1><span>Plus</span>Verkstaden</h1>
		<i class="fa fa-wrench"></i>
	</div>
</header>

WebContent/WEB-INF/jsp/plusverkstaden/page-title.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<header><h1><c:out value="${param.title}" /></h1></header>

WebContent/WEB-INF/jsp/plusverkstaden/styles.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="pvn" uri="se.plushogskolan.plusverkstaden" %>
<link rel="stylesheet" href="<% out.print(request.getContextPath()); %>/theme/styles/reset.css" />
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<link rel="stylesheet" href="<% out.print(request.getContextPath()); %>/theme/styles/plusverkstaden.css?${pvn:getRandomNumber()}" />

WebContent/WEB-INF/jsp/plusverkstaden/viewCar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html class="no-js">
	<head>
		<%@ include file="head.jsp" %>
		<%@ include file="styles.jsp" %>
	</head>
<body class="page-view-car">
	
	<%@ include file="page-header.jsp" %>
	<%@ include file="navigation.jsp" %>
	
	<section id="main">
		<div class="clearfix">
			<jsp:include page="page-title.jsp">
				<jsp:param name="title" value="${car.regNo}" />
			</jsp:include>
			<section class="car-info">
				<table>
					<caption>Car information</caption>
					<tr>
						<th>Year model</th>
						<td><c:out value="${car.yearModel}" /></td>
					</tr>
					<tr>
						<th>Brand</th>
						<td><c:out value="${car.brand}" /></td>
					</tr>
					<tr>
						<th>Fuel consumption</th>
						<td><c:out value="${car.fuelConsumption}" /></td>
					</tr>
			</table>
			</section>
			
			<section class="car-owner-info">
				<table>
					<caption>Owner information</caption>
					<tr>
						<th>Name</th>
						<td><c:out value="${car.owner.firstName} ${car.owner.lastName}" /></td>
					</tr>
					<tr>
						<th>SSN</th>
						<td><c:out value="${car.owner.socialSecurityNo}" /></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><c:out value="${car.owner.address}" /></td>
					</tr>
					<tr>
						<th>Zip code</th>
						<td><c:out value="${car.owner.zipCode}" /></td>
					</tr>
					<tr>
						<th>City</th>
						<td><c:out value="${car.owner.city}" /></td>
					</tr>
				</table>
			</section>
		</div>
	</section>
	
	<%@ include file="footer.jsp" %>
</body>
</html>